version: "3"
volumes:
    phpsocket:
services:
    http:
        container_name: "http"
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./server:/var/www
            - ./docker/http/ssl:/etc/nginx/ssl
            - ./docker/http/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/http/sites-available:/etc/nginx/sites-available
